services:
  # Database
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "4242:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./server/backups:/backups

volumes:
  postgres_data:
