services:
  # db:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "4242:5432"
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #     - ./server/backups:/backups
  #   container_name: pawgo_db
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    container_name: pawgo_redis


volumes:
  # postgres_data:
  redis_data:
